export const GET_HISTORY = 'GET_HISTORY';

export const FETCH_REQUEST_COUNTRY = 'FETCH_REQUEST_COUNTRY';
export const FETCH_RESOLVE_COUNTRY = 'FETCH_RESOLVE_COUNTRY';
export const FETCH_RESOLVE = 'FETCH_RESOLVE';
